[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[programs.localnet]
orbital_pulse = "3o6We5WQoGDM6wpQMPq5VE3fjvC7zgCUD56X12vLn917"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "SysvarS1otHashes111111111111111111111111111"
