[package]
name = "orbital_pulse"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "orbital_pulse"

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
# Жестко фиксируем borsh здесь
borsh = "=1.5.1"
borsh-derive = "=1.5.1"
solana-program = "=1.17.0"
